# Generated by Django 3.2.19 on 2023-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='default/def.jpg', null=True, upload_to='profile_pic/')),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=50, null=True)),
                ('phone_no', models.TextField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.TextField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('christian', 'christian'), ('Buddha', 'Buddha')], max_length=9)),
            ],
        ),
    ]
